stages:
  - build
  - deploy

before_script:
  # Configura la clave SSH para acceder al servidor
  - eval $(ssh-agent -s)
  - echo "$SSH_PRIVATE_KEY_BASE64" | base64 --decode > /tmp/id_rsa
  - chmod 600 /tmp/id_rsa
  - ssh-add /tmp/id_rsa
  - mkdir -p ~/.ssh
  - ssh-keyscan -H 104.236.112.158 >> ~/.ssh/known_hosts

  # Instalar y usar la versión de Node.js
  - curl -o- https://raw.githubusercontent.com/nvm-sh/nvm/v0.39.1/install.sh | bash
  - source ~/.nvm/nvm.sh
  - nvm install 20.17.0 # Cambia a la versión que usas localmente
  - nvm use 20.17.0

# Etapa de build
build:
  stage: build
  script:
    # Instala dependencias y compila el proyecto (si es necesario)
    echo "Instalando dependencias..."
    - npm install

  artifacts:
    paths:
      - node_modules/
      - dist/

# Etapa de deploy
deploy:
  stage: deploy
  script:
    # Copiar los archivos al servidor
    - scp -r . root@104.236.112.158:/root/monet/monetmex-back
    # Exportar las variables de GitLab CI/CD al servidor
    - ssh root@104.236.112.158 "echo 'export DB_HOST=$DB_HOST' >> /etc/environment"
    - ssh root@104.236.112.158 "echo 'export DB_USER=$DB_USER' >> /etc/environment"
    - ssh root@104.236.112.158 "echo 'export DB_PASSWORD=$DB_PASSWORD' >> /etc/environment"
    - ssh root@104.236.112.158 "echo 'export DB_NAME=$DB_NAME' >> /etc/environment"
    # Instalar dependencias
    - ssh root@104.236.112.158 'cd /root/monet/monetmex-back && npm install'
    # Ejecutar PM2 con el archivo ecosystem.config.js
    - ssh root@104.236.112.158 'cd /root/monet/monetmex-back && pm2 start ecosystem.config.js --env production && pm2 save'
  only:
    - main
