stages:
  - build
  - deploy

before_script:
  # Configura la clave SSH para acceder al servidor
  - eval $(ssh-agent -s)
  - echo "$SSH_PRIVATE_KEY_BASE64" | base64 --decode > /tmp/id_rsa
  - chmod 600 /tmp/id_rsa
  - ssh-add /tmp/id_rsa
  - mkdir -p ~/.ssh
  - ssh-keyscan -H 104.236.112.158 >> ~/.ssh/known_hosts

  # Instalar y usar la versión de Node.js
  - curl -o- https://raw.githubusercontent.com/nvm-sh/nvm/v0.39.1/install.sh | bash
  - source ~/.nvm/nvm.sh
  - nvm install 20.17.0 # Cambia a la versión que usas localmente
  - nvm use 20.17.0

# Etapa de build
build:
  stage: build
  script:
    # Instala dependencias y compila el proyecto (si es necesario)
    echo "Instalando dependencias..."
    - npm install

  artifacts:
    paths:
      - node_modules/
      - dist/

# Etapa de deploy
deploy:
  stage: deploy
  script:
    # Copiar los archivos al servidor
    - scp -r . root@104.236.112.158:/root/monet/monetmex-back
    # Establecer las variables de entorno en el servidor
    - ssh root@104.236.112.158 'echo "DB_HOST=$DB_HOST" >> /root/.bashrc'
    - ssh root@104.236.112.158 'echo "DB_USER=$DB_USER" >> /root/.bashrc'
    - ssh root@104.236.112.158 'echo "DB_PASSWORD=$DB_PASSWORD" >> /root/.bashrc'
    - ssh root@104.236.112.158 'echo "DB_NAME=$DB_NAME" >> /root/.bashrc'
    # Instalar dependencias y ejecutar PM2
    - ssh root@104.236.112.158 'cd /root/monet/monetmex-back && npm install && pm2 restart monetmex-back -f && pm2 save'
  only:
    - main


